// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9vYm5Y58M2LMTCZ-KhEKXECW9dlCdV4A',
    appId: '1:167855978354:web:a3e8d0260515c11c6acfeb',
    messagingSenderId: '167855978354',
    projectId: 'reddit-clone-6d505',
    authDomain: 'reddit-clone-6d505.firebaseapp.com',
    storageBucket: 'reddit-clone-6d505.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlFOe3gNeckuaUdUtyb3LjWoa0hTQtfio',
    appId: '1:167855978354:android:42cd24d4d9d5e5ac6acfeb',
    messagingSenderId: '167855978354',
    projectId: 'reddit-clone-6d505',
    storageBucket: 'reddit-clone-6d505.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdrXuP8jVmB-19PwI3LcjdHbePmUo61LQ',
    appId: '1:167855978354:ios:1ba0fb4fb312f5876acfeb',
    messagingSenderId: '167855978354',
    projectId: 'reddit-clone-6d505',
    storageBucket: 'reddit-clone-6d505.appspot.com',
    iosBundleId: 'com.example.reddClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9vYm5Y58M2LMTCZ-KhEKXECW9dlCdV4A',
    appId: '1:167855978354:web:2039b6cd95b454fc6acfeb',
    messagingSenderId: '167855978354',
    projectId: 'reddit-clone-6d505',
    authDomain: 'reddit-clone-6d505.firebaseapp.com',
    storageBucket: 'reddit-clone-6d505.appspot.com',
  );
}
